using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HotFix_Project
{
    public class TimerManager : AutoGeneratedSingleton<TimerManager>
    {
        // 用一颗树记录当前游戏内的所有的Timer对象

        private LinkedList<Timer> m_timerLinkList = new LinkedList<Timer>();

        public void Initialization()
        {
            m_timerLinkList.Clear();
        }

        public void Update(float deltaTime)
        {
            IEnumerator<Timer> timers = m_timerLinkList.GetEnumerator();
            while (timers.MoveNext())
            {
                if (timers.Current != null)
                {
                    timers.Current.Process(deltaTime);
                }
            }
        }



        public void Release()
        {
            m_timerLinkList.Clear();
        }

    }
}
