using HotFix_Project.UI.UICore;
using System.Collections.Generic;

namespace HotFix_Project
{
    public class UIManager : Utils.AutoGeneratedSingleton<UIManager>
    {
        private bool m_enable = false;

        #region Root


        #endregion

        private Stack<string> m_canvasStack = new Stack<string>();

        private Stack<string> m_windowStack = new Stack<string>();

        #region 生命周期
        public void Initialization()
        {

        }

        public void Update(float deltaTime)
        {
            if (!m_enable) return;
        }

        public void Release()
        {

        }
        #endregion


        public void OpenUI<T>() where T : UiBase
        {

        }


    }
}
