using ILRuntime.CLR.TypeSystem;
using ILRuntime.CLR.Method;
using ILRuntime.Runtime.Enviorment;

public class MonoBehaviourManger : AutoGeneratedSingleton<MonoBehaviourManger>
{
    private const string typeStr = "HotFix_Project.MonoBehaviourController";

    public void Awake()
    {
        // 预先获得IMethod，可以减低每次调用查找方法耗用的时间
        // InstantiateType = HotFixMgr.Instance.AppDomain.LoadedTypes[typeStr];
        // 第二种方式
        // InstantiateObj = ((ILType) InstantiateType).Instantiate();

        CallMethod("Awake");
    }

    public  void OnEnable()
    {
        CallMethod("OnEnable");
    }

    public void Start()
    {
        CallMethod("Start");
    }

    public void Update()
    {
        CallMethod("Update");
    }

    public void FixedUpdate()
    {
        CallMethod("FixedUpdate");
    }

    public void LateUpdate()
    {
        CallMethod("LateUpdate");
    }

    public void OnDisable()
    {
        CallMethod("OnDisable");
    }

    public void OnDestroy()
    {
        CallMethod("OnDestroy");
    }
    
    private void CallMethod(string methodName)
    {
        HotFixMgr.Instance.AppDomain.Invoke(typeStr, methodName, null, null);
    }
}