using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using UnityEngine.Networking;



public class WebRequestManager : AutoGeneratedSingleton<WebRequestManager>
{
    
    /// <summary>
    /// 请求下载 一个文件
    /// </summary>
    /// <param name="requestFile"></param>
    /// <param name="path"></param>
    /// <returns></returns>
    public IEnumerator CreateDownloadFileRequest(string requestFile, string path)
    {
        if (File.Exists(path))
        {
            File.Delete(path);
        }
        
        UnityWebRequest request = new UnityWebRequest("");
        request.method = UnityWebRequest.kHttpVerbGET;
        request.timeout = 5;
        request.SetRequestHeader("file",requestFile);
        
        DownloadHandlerFile handle = new DownloadHandlerFile(path);
        handle.removeFileOnAbort = true;
        request.downloadHandler = new DownloadHandlerFile(path);
        yield return request.SendWebRequest();
    }
    
    
    
}