using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AutoGeneratedMonoSingleton<T> : MonoBehaviour where T : AutoGeneratedMonoSingleton<T>
{
    private static T m_instance = null;

    public static T Instance
    {
        get
        {
            if (m_instance != null)
            {
                return m_instance;
            }

            CreateInstance();
            return m_instance;
        }
    }

    public virtual void Init()
    {
        
    }

    private static void CreateInstance()
    {
        if(m_instance != null) return;
        
        GameObject go = new GameObject(typeof(T).FullName);
        m_instance = go.GetComponent<T>();
        if (m_instance == null)
        {
            m_instance = go.AddComponent<T>();
        }
        DontDestroyOnLoad(go);
        go.transform.localPosition = Vector3.zero;
        go.transform.localScale = Vector3.zero;
        go.transform.localRotation = Quaternion.identity;
    }
}
