using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;

public class AssetBundleManager : UnityAutoGeneratedSingleton<AssetBundleManager>
{
    // Start is called before the first frame update
    public void Start()
    {
        // string bundleName = "ui/logic/gamecontroller";
        //
        // string path = Path.Combine(GameConfigData.GetPlatformResRootPath(), $"AssetBundle/{bundleName}");
        // AssetBundle asset = AssetBundle.LoadFromFile(path);
        //
        // GameObject obj = asset.LoadAsset<GameObject>("GameController");
    }


}
